- name: Create infrastructure w/ terraform
  hosts: localhost
  tasks:
    - name: Run terraform
      terraform:
        project_path: "../terraform"
        force_init: yes
        state: present
      register: trfrm

    - name: Add docker host
      add_host:
        name: docker_server
        groups: nodes
        ansible_host: "{{ trfrm.outputs.docker.value.docker_server_ip4 }}"
        ansible_ssh_private_key_file: ~/.ssh/sung_ar
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Get secrets from vault
  hosts: localhost
  tasks:
    - name: Get bot secrets from vault
      community.hashi_vault.vault_kv2_get:
        url: "http://localhost:8200"
        path: tgbot
      register: tgbot

    - name: Get api secrets from vault
      community.hashi_vault.vault_kv2_get:
        url: "http://localhost:8200"
        path: api
      register: api

    - name: Get db secrets from vault
      community.hashi_vault.vault_kv2_get:
        url: "http://localhost:8200"
        path: database
      register: database

- name: Wait out the timeout for creating docker instance
  hosts: localhost
  connection: local
  tasks:
    - name: Wait for db port 22
      wait_for:
        host: "{{ trfrm.outputs.docker.value.docker_server_ip4}}"
        port: 22

- name: Configure docker host
  hosts: docker_server
  vars:
    db_name: "{{ hostvars.localhost.database.secret.db_name }}"
    db_user: "{{ hostvars.localhost.database.secret.db_user }}"
    db_password: "{{ hostvars.localhost.database.secret.db_password }}"
    cheque_api_token: "{{ hostvars.localhost.api.secret.token }}"
    telegram_api_token: "{{ hostvars.localhost.tgbot.secret.token }}"

  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Transfer docker-compose file
      ansible.builtin.template:
        src: ./templates/compose.yaml.j2
        dest: ./compose.yaml

    - name: Transfer sql backup
      ansible.builtin.template:
        src: ./templates/cheque_db.psql.j2
        dest: ./cheque_db.psql

    - name: Run docker-compose
      community.docker.docker_compose:
        definition: ./compose.yaml
