- name: Add k8s host
  hosts: localhost
  tasks:
    - name: Add k8s host
      add_host:
        name: k8s_server
        groups: nodes
        ansible_host: 192.168.199.216
        ansible_ssh_private_key_file: ~/.ssh/k8s
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Get secrets from vault
  hosts: localhost
  tasks:
    - name: Get bot secrets from vault
      community.hashi_vault.vault_kv2_get:
        url: "http://localhost:8200"
        path: tgbot
      register: tgbot

    - name: Get api secrets from vault
      community.hashi_vault.vault_kv2_get:
        url: "http://localhost:8200"
        path: api
      register: api

    - name: Get db secrets from vault
      community.hashi_vault.vault_kv2_get:
        url: "http://localhost:8200"
        path: database
      register: database

- name: Check availability of k8s host
  hosts: localhost
  connection: local
  tasks:
    - name: Wait for k8s port 22
      wait_for:
        host: "192.168.199.216"
        port: 22

- name: Deploy pods
  hosts: k8s_server
  vars:
    db_name: "{{ hostvars.localhost.database.secret.db_name }}"
    db_user: "{{ hostvars.localhost.database.secret.db_user }}"
    db_password: "{{ hostvars.localhost.database.secret.db_password }}"
    cheque_api_token: "{{ hostvars.localhost.api.secret.token }}"
    telegram_api_token: "{{ hostvars.localhost.tgbot.secret.token }}"

  tasks:
    - name: Transfer api deployment file
      ansible.builtin.template:
        src: ./templates/api-deployment.yaml
        dest: ~/cheque_check/api-deployment.yaml

    - name: Transfer api service file
      ansible.builtin.template:
        src: ./templates/api-service.yaml
        dest: ~/cheque_check/api-service.yaml

    - name: Transfer database deployment file
      ansible.builtin.template:
        src: ./templates/database-deployment.yaml
        dest: ~/cheque_check/database-deployment.yaml

    - name: Transfer database service file
      ansible.builtin.template:
        src: ./templates/database-service.yaml
        dest: ~/cheque_check/database-service.yaml

    - name: Transfer database volume file
      ansible.builtin.template:
        src: ./templates/database-volume.yaml
        dest: ~/cheque_check/database-volume.yaml

    - name: Transfer database volume claim file
      ansible.builtin.template:
        src: ./templates/database-pv-claim.yaml
        dest: ~/cheque_check/database-pv-claim.yaml

    - name: Transfer tgbot deployment file
      ansible.builtin.template:
        src: ./templates/tgbot-deployment.yaml
        dest: ~/cheque_check/tgbot-deployment.yaml

    - name: Transfer api service file
      ansible.builtin.template:
        src: ./templates/api-service.yaml
        dest: ~/cheque_check/api-service.yaml

